name: Test cos of 0 on Mac with Homebrew

on:
  push:
    branches: ['*']
    tags: 
  pull_request:
  release:
    types: ['created']

defaults:
  run:
    shell: bash
jobs:
  build:
    name: Compiling from source on macOS with MacPorts
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Install macOS prerequesites via Homebrew
      run: |
           uname -a
           brew update
           brew install libsndfile
           brew install portaudio
           brew install liblo
           brew install eigen

    - name: Compile our test program
      run: |
           clang++ -Wall -Wextra -Wnon-virtual-dtor -Wformat -Werror -std=c++17 -fPIC -O3 -msse -msse2 -mfpmath=sse -ffast-math -fomit-frame-pointer -fno-finite-math-only -Wno-error=unused-command-line-argument -Wimplicit-fallthrough -g -Wno-unknown-warning-option -Wno-duplicated-branches -fno-unsafe-math-optimizations -c -o hanning.o hanning.cpp
           clang++ -Wall -Wextra -Wnon-virtual-dtor -Wformat -Werror -std=c++17 -fPIC -O3 -msse -msse2 -mfpmath=sse -ffast-math -fomit-frame-pointer -fno-finite-math-only -Wno-error=unused-command-line-argument -Wimplicit-fallthrough -g -Wno-unknown-warning-option -Wno-duplicated-branches -fno-unsafe-math-optimizations -c -o main.o main.cpp
           clang++ -Wall -Wextra -Wnon-virtual-dtor -Wformat -Werror -std=c++17 -fPIC -O3 -msse -msse2 -mfpmath=sse -ffast-math -fomit-frame-pointer -fno-finite-math-only -isystem/opt/local/include -Wno-error=unused-command-line-argument -Wimplicit-fallthrough -g -c -o main.o main.cpp
           clang++ -rpath @executable_path -o a.out main.o hanning.o -L/opt/local/lib -ldl -lpthread
           ./a.out
